[{"name": "test.test_radial_fade.RadialFade.test_center", "status": "passed", "message": "", "passed": true, "points": ["p03-12.1"], "backtrace": []}, {"name": "test.test_radial_fade.RadialFade.test_main", "status": "passed", "message": "", "passed": true, "points": ["p03-12.2"], "backtrace": []}, {"name": "test.test_radial_fade.RadialFade.test_radial_distance", "status": "passed", "message": "", "passed": true, "points": ["p03-12.1"], "backtrace": []}, {"name": "test.test_radial_fade.RadialFade.test_radial_fade", "status": "passed", "message": "", "passed": true, "points": ["p03-12.2"], "backtrace": []}, {"name": "test.test_radial_fade.RadialFade.test_radial_mask", "status": "failed", "message": "0.0 != 1.0 : Value of the radial mask should be 1 in the center!", "passed": false, "points": ["p03-12.2"], "backtrace": ["  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 615, in run\n    testMethod()\n", "  File \"/home/vins/TMC/week2/hy-data-analysis-with-python-summer-2019/part03-e12_radial_fade/test/test_radial_fade.py\", line 71, in test_radial_mask\n    self.assertEqual(rm[cy, cx], 1.0, msg=\"Value of the radial mask should be 1 in the center!\")\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 839, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 832, in _baseAssertEqual\n    raise self.failureException(msg)\n"]}, {"name": "test.test_radial_fade.RadialFade.test_radial_mask_size_one", "status": "failed", "message": "0.0 != 1.0 : Are you sure the radial_mask function works correctly for arrays of size 1", "passed": false, "points": ["p03-12.2"], "backtrace": ["  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 615, in run\n    testMethod()\n", "  File \"/home/vins/TMC/week2/hy-data-analysis-with-python-summer-2019/part03-e12_radial_fade/test/test_radial_fade.py\", line 78, in test_radial_mask_size_one\n    self.assertEqual(rm[0,0], 1.0, msg=\"Are you sure the radial_mask function works correctly for arrays of size 1\")\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 839, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 832, in _baseAssertEqual\n    raise self.failureException(msg)\n"]}]